version: '3.8'

services:
  postgres:
    env_file:
      - db.env
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data


  backend:
    env_file:
      - .development.env
    container_name: backend
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"


  pgadmin:
    env_file:
      - pgadmin.env
    image: dpage/pgadmin4
    restart: always
    ports:
      - "82:80"

volumes:
  postgres: # create the volume for persisting data.